name: 🚀 Feature Request
description: Suggest a new feature or tool for CAYC BAKE
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.
        
        💡 **Tip**: Check if your feature has already been requested in existing issues.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Security Tool
        - Scanner Enhancement
        - Payload Generator
        - Workflow Improvement
        - Documentation
        - Installation/Setup
        - Performance Optimization
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Currently, I cannot..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this feature to work
      placeholder: "It would be great if..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Provide a specific example of how you'd use this feature
      placeholder: "When testing X, I would use this feature to..."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my work)
        - High (Would significantly improve workflow)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      options:
        - label: This follows legal and ethical guidelines
          required: true
        - label: I'm willing to help implement this feature
        - label: This requires new dependencies
        - label: This might break existing functionality

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
